project_id = "uykzfpzawuyaroksyjsc"

[functions.get-users]
verify_jwt = false

[functions.get-user-activity]
verify_jwt = false

[functions.update-user-profile]
verify_jwt = false

[functions.fetch-exchange-rate]
verify_jwt = false

[functions.public-booking-availability]
verify_jwt = false

[functions.public-booking-create]
verify_jwt = false

[functions.public-booking-webhook]
verify_jwt = false
