project_id = "uykzfpzawuyaroksyjsc"

[functions.get-users]
verify_jwt = false

[functions.get-user-activity]
verify_jwt = false

[functions.update-user-profile]
verify_jwt = false

[functions.fetch-exchange-rate]
verify_jwt = false

[functions.public-booking-availability]
verify_jwt = false

[functions.public-booking-create]
verify_jwt = false

[functions.public-booking-webhook]
verify_jwt = false

[functions.internal-booking-availability]
verify_jwt = false

[functions.internal-booking-create]
verify_jwt = false

[functions.internal-calendar-bookings]
verify_jwt = false

[functions.internal-calendar-booking-cancel]
verify_jwt = false

[functions.internal-calendar-booking-reschedule]
verify_jwt = false

[functions.internal-reservation-details]
verify_jwt = false

[functions.internal-team-member-reservation-oversight]
verify_jwt = false
